### ISSUE TITLE
Restart of NordVPN daemon hangs

### ISSUE THREAD

**Issue by jess192** [jess192/pothos#3]
NordVPN daemon restart (`pothos -f`) from PR #2 hangs since this command is attempting to get NordVPN status (`nordvpn status`) in order to determine if a restart is in order, but that is also hanging. 

Possible solution: Restart daemon after not getting a response from NordVPN status after 30 seconds (or less), instead of waiting to see if NordVPN is disconnected, since NordVPN tends to hang in these scenarios.

**Comment by roboto84** [comment]
got it, i'll make it happen, thanks for the feedback.
